services:
  backend_dev:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/api:/app
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=debugPass
      - DEV=true
    env_file:
      - .env
    depends_on:
      - postgres_dev
    networks:
      - gonext_network_dev

  postgres_dev:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gonext_dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - gonext_network_dev

volumes:
  postgres_data_dev:


networks:
  gonext_network_dev:
    driver: bridge
