// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoNext/base/ent/exercise"
	"GoNext/base/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExerciseUpdate is the builder for updating Exercise entities.
type ExerciseUpdate struct {
	config
	hooks    []Hook
	mutation *ExerciseMutation
}

// Where appends a list predicates to the ExerciseUpdate builder.
func (eu *ExerciseUpdate) Where(ps ...predicate.Exercise) *ExerciseUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *ExerciseUpdate) SetUpdatedAt(t time.Time) *ExerciseUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetName sets the "name" field.
func (eu *ExerciseUpdate) SetName(s string) *ExerciseUpdate {
	eu.mutation.SetName(s)
	return eu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (eu *ExerciseUpdate) SetNillableName(s *string) *ExerciseUpdate {
	if s != nil {
		eu.SetName(*s)
	}
	return eu
}

// SetVideoURL sets the "video_url" field.
func (eu *ExerciseUpdate) SetVideoURL(s string) *ExerciseUpdate {
	eu.mutation.SetVideoURL(s)
	return eu
}

// SetNillableVideoURL sets the "video_url" field if the given value is not nil.
func (eu *ExerciseUpdate) SetNillableVideoURL(s *string) *ExerciseUpdate {
	if s != nil {
		eu.SetVideoURL(*s)
	}
	return eu
}

// ClearVideoURL clears the value of the "video_url" field.
func (eu *ExerciseUpdate) ClearVideoURL() *ExerciseUpdate {
	eu.mutation.ClearVideoURL()
	return eu
}

// SetImageURL sets the "image_url" field.
func (eu *ExerciseUpdate) SetImageURL(s string) *ExerciseUpdate {
	eu.mutation.SetImageURL(s)
	return eu
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (eu *ExerciseUpdate) SetNillableImageURL(s *string) *ExerciseUpdate {
	if s != nil {
		eu.SetImageURL(*s)
	}
	return eu
}

// ClearImageURL clears the value of the "image_url" field.
func (eu *ExerciseUpdate) ClearImageURL() *ExerciseUpdate {
	eu.mutation.ClearImageURL()
	return eu
}

// Mutation returns the ExerciseMutation object of the builder.
func (eu *ExerciseUpdate) Mutation() *ExerciseMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *ExerciseUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *ExerciseUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *ExerciseUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *ExerciseUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *ExerciseUpdate) defaults() {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		v := exercise.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *ExerciseUpdate) check() error {
	if v, ok := eu.mutation.VideoURL(); ok {
		if err := exercise.VideoURLValidator(v); err != nil {
			return &ValidationError{Name: "video_url", err: fmt.Errorf(`ent: validator failed for field "Exercise.video_url": %w`, err)}
		}
	}
	if v, ok := eu.mutation.ImageURL(); ok {
		if err := exercise.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Exercise.image_url": %w`, err)}
		}
	}
	return nil
}

func (eu *ExerciseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(exercise.Table, exercise.Columns, sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(exercise.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := eu.mutation.Name(); ok {
		_spec.SetField(exercise.FieldName, field.TypeString, value)
	}
	if value, ok := eu.mutation.VideoURL(); ok {
		_spec.SetField(exercise.FieldVideoURL, field.TypeString, value)
	}
	if eu.mutation.VideoURLCleared() {
		_spec.ClearField(exercise.FieldVideoURL, field.TypeString)
	}
	if value, ok := eu.mutation.ImageURL(); ok {
		_spec.SetField(exercise.FieldImageURL, field.TypeString, value)
	}
	if eu.mutation.ImageURLCleared() {
		_spec.ClearField(exercise.FieldImageURL, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exercise.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// ExerciseUpdateOne is the builder for updating a single Exercise entity.
type ExerciseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExerciseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *ExerciseUpdateOne) SetUpdatedAt(t time.Time) *ExerciseUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetName sets the "name" field.
func (euo *ExerciseUpdateOne) SetName(s string) *ExerciseUpdateOne {
	euo.mutation.SetName(s)
	return euo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (euo *ExerciseUpdateOne) SetNillableName(s *string) *ExerciseUpdateOne {
	if s != nil {
		euo.SetName(*s)
	}
	return euo
}

// SetVideoURL sets the "video_url" field.
func (euo *ExerciseUpdateOne) SetVideoURL(s string) *ExerciseUpdateOne {
	euo.mutation.SetVideoURL(s)
	return euo
}

// SetNillableVideoURL sets the "video_url" field if the given value is not nil.
func (euo *ExerciseUpdateOne) SetNillableVideoURL(s *string) *ExerciseUpdateOne {
	if s != nil {
		euo.SetVideoURL(*s)
	}
	return euo
}

// ClearVideoURL clears the value of the "video_url" field.
func (euo *ExerciseUpdateOne) ClearVideoURL() *ExerciseUpdateOne {
	euo.mutation.ClearVideoURL()
	return euo
}

// SetImageURL sets the "image_url" field.
func (euo *ExerciseUpdateOne) SetImageURL(s string) *ExerciseUpdateOne {
	euo.mutation.SetImageURL(s)
	return euo
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (euo *ExerciseUpdateOne) SetNillableImageURL(s *string) *ExerciseUpdateOne {
	if s != nil {
		euo.SetImageURL(*s)
	}
	return euo
}

// ClearImageURL clears the value of the "image_url" field.
func (euo *ExerciseUpdateOne) ClearImageURL() *ExerciseUpdateOne {
	euo.mutation.ClearImageURL()
	return euo
}

// Mutation returns the ExerciseMutation object of the builder.
func (euo *ExerciseUpdateOne) Mutation() *ExerciseMutation {
	return euo.mutation
}

// Where appends a list predicates to the ExerciseUpdate builder.
func (euo *ExerciseUpdateOne) Where(ps ...predicate.Exercise) *ExerciseUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *ExerciseUpdateOne) Select(field string, fields ...string) *ExerciseUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Exercise entity.
func (euo *ExerciseUpdateOne) Save(ctx context.Context) (*Exercise, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *ExerciseUpdateOne) SaveX(ctx context.Context) *Exercise {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *ExerciseUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *ExerciseUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *ExerciseUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		v := exercise.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *ExerciseUpdateOne) check() error {
	if v, ok := euo.mutation.VideoURL(); ok {
		if err := exercise.VideoURLValidator(v); err != nil {
			return &ValidationError{Name: "video_url", err: fmt.Errorf(`ent: validator failed for field "Exercise.video_url": %w`, err)}
		}
	}
	if v, ok := euo.mutation.ImageURL(); ok {
		if err := exercise.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Exercise.image_url": %w`, err)}
		}
	}
	return nil
}

func (euo *ExerciseUpdateOne) sqlSave(ctx context.Context) (_node *Exercise, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exercise.Table, exercise.Columns, sqlgraph.NewFieldSpec(exercise.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Exercise.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exercise.FieldID)
		for _, f := range fields {
			if !exercise.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exercise.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(exercise.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := euo.mutation.Name(); ok {
		_spec.SetField(exercise.FieldName, field.TypeString, value)
	}
	if value, ok := euo.mutation.VideoURL(); ok {
		_spec.SetField(exercise.FieldVideoURL, field.TypeString, value)
	}
	if euo.mutation.VideoURLCleared() {
		_spec.ClearField(exercise.FieldVideoURL, field.TypeString)
	}
	if value, ok := euo.mutation.ImageURL(); ok {
		_spec.SetField(exercise.FieldImageURL, field.TypeString, value)
	}
	if euo.mutation.ImageURLCleared() {
		_spec.ClearField(exercise.FieldImageURL, field.TypeString)
	}
	_node = &Exercise{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exercise.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
