// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoNext/base/ent/exercise"
	"GoNext/base/ent/schema"
	"GoNext/base/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exerciseMixin := schema.Exercise{}.Mixin()
	exerciseMixinFields0 := exerciseMixin[0].Fields()
	_ = exerciseMixinFields0
	exerciseFields := schema.Exercise{}.Fields()
	_ = exerciseFields
	// exerciseDescCreatedAt is the schema descriptor for created_at field.
	exerciseDescCreatedAt := exerciseMixinFields0[0].Descriptor()
	// exercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	exercise.DefaultCreatedAt = exerciseDescCreatedAt.Default.(func() time.Time)
	// exerciseDescUpdatedAt is the schema descriptor for updated_at field.
	exerciseDescUpdatedAt := exerciseMixinFields0[1].Descriptor()
	// exercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exercise.DefaultUpdatedAt = exerciseDescUpdatedAt.Default.(func() time.Time)
	// exercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exercise.UpdateDefaultUpdatedAt = exerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exerciseDescVideoURL is the schema descriptor for video_url field.
	exerciseDescVideoURL := exerciseFields[1].Descriptor()
	// exercise.VideoURLValidator is a validator for the "video_url" field. It is called by the builders before save.
	exercise.VideoURLValidator = exerciseDescVideoURL.Validators[0].(func(string) error)
	// exerciseDescImageURL is the schema descriptor for image_url field.
	exerciseDescImageURL := exerciseFields[2].Descriptor()
	// exercise.ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	exercise.ImageURLValidator = exerciseDescImageURL.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescFirstname is the schema descriptor for firstname field.
	userDescFirstname := userFields[1].Descriptor()
	// user.FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	user.FirstnameValidator = userDescFirstname.Validators[0].(func(string) error)
	// userDescLastname is the schema descriptor for lastname field.
	userDescLastname := userFields[2].Descriptor()
	// user.LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	user.LastnameValidator = userDescLastname.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[4].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
