// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoNext/base/ent/exercise"
	"GoNext/base/ent/program"
	"GoNext/base/ent/schema"
	"GoNext/base/ent/user"
	"GoNext/base/ent/workout"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exerciseMixin := schema.Exercise{}.Mixin()
	exerciseMixinFields0 := exerciseMixin[0].Fields()
	_ = exerciseMixinFields0
	exerciseFields := schema.Exercise{}.Fields()
	_ = exerciseFields
	// exerciseDescCreatedAt is the schema descriptor for created_at field.
	exerciseDescCreatedAt := exerciseMixinFields0[0].Descriptor()
	// exercise.DefaultCreatedAt holds the default value on creation for the created_at field.
	exercise.DefaultCreatedAt = exerciseDescCreatedAt.Default.(func() time.Time)
	// exerciseDescUpdatedAt is the schema descriptor for updated_at field.
	exerciseDescUpdatedAt := exerciseMixinFields0[1].Descriptor()
	// exercise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exercise.DefaultUpdatedAt = exerciseDescUpdatedAt.Default.(func() time.Time)
	// exercise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exercise.UpdateDefaultUpdatedAt = exerciseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exerciseDescURL is the schema descriptor for url field.
	exerciseDescURL := exerciseFields[1].Descriptor()
	// exercise.URLValidator is a validator for the "url" field. It is called by the builders before save.
	exercise.URLValidator = exerciseDescURL.Validators[0].(func(string) error)
	programMixin := schema.Program{}.Mixin()
	programMixinFields0 := programMixin[0].Fields()
	_ = programMixinFields0
	programFields := schema.Program{}.Fields()
	_ = programFields
	// programDescCreatedAt is the schema descriptor for created_at field.
	programDescCreatedAt := programMixinFields0[0].Descriptor()
	// program.DefaultCreatedAt holds the default value on creation for the created_at field.
	program.DefaultCreatedAt = programDescCreatedAt.Default.(func() time.Time)
	// programDescUpdatedAt is the schema descriptor for updated_at field.
	programDescUpdatedAt := programMixinFields0[1].Descriptor()
	// program.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	program.DefaultUpdatedAt = programDescUpdatedAt.Default.(func() time.Time)
	// program.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	program.UpdateDefaultUpdatedAt = programDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	workoutMixin := schema.Workout{}.Mixin()
	workoutMixinFields0 := workoutMixin[0].Fields()
	_ = workoutMixinFields0
	workoutFields := schema.Workout{}.Fields()
	_ = workoutFields
	// workoutDescCreatedAt is the schema descriptor for created_at field.
	workoutDescCreatedAt := workoutMixinFields0[0].Descriptor()
	// workout.DefaultCreatedAt holds the default value on creation for the created_at field.
	workout.DefaultCreatedAt = workoutDescCreatedAt.Default.(func() time.Time)
	// workoutDescUpdatedAt is the schema descriptor for updated_at field.
	workoutDescUpdatedAt := workoutMixinFields0[1].Descriptor()
	// workout.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workout.DefaultUpdatedAt = workoutDescUpdatedAt.Default.(func() time.Time)
	// workout.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workout.UpdateDefaultUpdatedAt = workoutDescUpdatedAt.UpdateDefault.(func() time.Time)
}
