// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoNext/base/ent/predicate"
	"GoNext/base/ent/user"
	"GoNext/base/ent/workout"
	"GoNext/base/ent/workoutexercise"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkoutUpdate is the builder for updating Workout entities.
type WorkoutUpdate struct {
	config
	hooks    []Hook
	mutation *WorkoutMutation
}

// Where appends a list predicates to the WorkoutUpdate builder.
func (wu *WorkoutUpdate) Where(ps ...predicate.Workout) *WorkoutUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WorkoutUpdate) SetUpdatedAt(t time.Time) *WorkoutUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetName sets the "name" field.
func (wu *WorkoutUpdate) SetName(s string) *WorkoutUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableName(s *string) *WorkoutUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// ClearName clears the value of the "name" field.
func (wu *WorkoutUpdate) ClearName() *WorkoutUpdate {
	wu.mutation.ClearName()
	return wu
}

// SetActive sets the "active" field.
func (wu *WorkoutUpdate) SetActive(b bool) *WorkoutUpdate {
	wu.mutation.SetActive(b)
	return wu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableActive(b *bool) *WorkoutUpdate {
	if b != nil {
		wu.SetActive(*b)
	}
	return wu
}

// SetUserID sets the "user_id" field.
func (wu *WorkoutUpdate) SetUserID(u uuid.UUID) *WorkoutUpdate {
	wu.mutation.SetUserID(u)
	return wu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wu *WorkoutUpdate) SetNillableUserID(u *uuid.UUID) *WorkoutUpdate {
	if u != nil {
		wu.SetUserID(*u)
	}
	return wu
}

// ClearUserID clears the value of the "user_id" field.
func (wu *WorkoutUpdate) ClearUserID() *WorkoutUpdate {
	wu.mutation.ClearUserID()
	return wu
}

// AddWorkoutExerciseIDs adds the "workout_exercise" edge to the WorkoutExercise entity by IDs.
func (wu *WorkoutUpdate) AddWorkoutExerciseIDs(ids ...int) *WorkoutUpdate {
	wu.mutation.AddWorkoutExerciseIDs(ids...)
	return wu
}

// AddWorkoutExercise adds the "workout_exercise" edges to the WorkoutExercise entity.
func (wu *WorkoutUpdate) AddWorkoutExercise(w ...*WorkoutExercise) *WorkoutUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.AddWorkoutExerciseIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (wu *WorkoutUpdate) SetUser(u *User) *WorkoutUpdate {
	return wu.SetUserID(u.ID)
}

// Mutation returns the WorkoutMutation object of the builder.
func (wu *WorkoutUpdate) Mutation() *WorkoutMutation {
	return wu.mutation
}

// ClearWorkoutExercise clears all "workout_exercise" edges to the WorkoutExercise entity.
func (wu *WorkoutUpdate) ClearWorkoutExercise() *WorkoutUpdate {
	wu.mutation.ClearWorkoutExercise()
	return wu
}

// RemoveWorkoutExerciseIDs removes the "workout_exercise" edge to WorkoutExercise entities by IDs.
func (wu *WorkoutUpdate) RemoveWorkoutExerciseIDs(ids ...int) *WorkoutUpdate {
	wu.mutation.RemoveWorkoutExerciseIDs(ids...)
	return wu
}

// RemoveWorkoutExercise removes "workout_exercise" edges to WorkoutExercise entities.
func (wu *WorkoutUpdate) RemoveWorkoutExercise(w ...*WorkoutExercise) *WorkoutUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.RemoveWorkoutExerciseIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (wu *WorkoutUpdate) ClearUser() *WorkoutUpdate {
	wu.mutation.ClearUser()
	return wu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkoutUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkoutUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkoutUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkoutUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WorkoutUpdate) defaults() {
	if _, ok := wu.mutation.UpdatedAt(); !ok {
		v := workout.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
}

func (wu *WorkoutUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workout.Table, workout.Columns, sqlgraph.NewFieldSpec(workout.FieldID, field.TypeUUID))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(workout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workout.FieldName, field.TypeString, value)
	}
	if wu.mutation.NameCleared() {
		_spec.ClearField(workout.FieldName, field.TypeString)
	}
	if value, ok := wu.mutation.Active(); ok {
		_spec.SetField(workout.FieldActive, field.TypeBool, value)
	}
	if wu.mutation.WorkoutExerciseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workout.WorkoutExerciseTable,
			Columns: []string{workout.WorkoutExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedWorkoutExerciseIDs(); len(nodes) > 0 && !wu.mutation.WorkoutExerciseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workout.WorkoutExerciseTable,
			Columns: []string{workout.WorkoutExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.WorkoutExerciseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workout.WorkoutExerciseTable,
			Columns: []string{workout.WorkoutExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UserTable,
			Columns: []string{workout.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UserTable,
			Columns: []string{workout.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkoutUpdateOne is the builder for updating a single Workout entity.
type WorkoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkoutMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WorkoutUpdateOne) SetUpdatedAt(t time.Time) *WorkoutUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetName sets the "name" field.
func (wuo *WorkoutUpdateOne) SetName(s string) *WorkoutUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableName(s *string) *WorkoutUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// ClearName clears the value of the "name" field.
func (wuo *WorkoutUpdateOne) ClearName() *WorkoutUpdateOne {
	wuo.mutation.ClearName()
	return wuo
}

// SetActive sets the "active" field.
func (wuo *WorkoutUpdateOne) SetActive(b bool) *WorkoutUpdateOne {
	wuo.mutation.SetActive(b)
	return wuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableActive(b *bool) *WorkoutUpdateOne {
	if b != nil {
		wuo.SetActive(*b)
	}
	return wuo
}

// SetUserID sets the "user_id" field.
func (wuo *WorkoutUpdateOne) SetUserID(u uuid.UUID) *WorkoutUpdateOne {
	wuo.mutation.SetUserID(u)
	return wuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wuo *WorkoutUpdateOne) SetNillableUserID(u *uuid.UUID) *WorkoutUpdateOne {
	if u != nil {
		wuo.SetUserID(*u)
	}
	return wuo
}

// ClearUserID clears the value of the "user_id" field.
func (wuo *WorkoutUpdateOne) ClearUserID() *WorkoutUpdateOne {
	wuo.mutation.ClearUserID()
	return wuo
}

// AddWorkoutExerciseIDs adds the "workout_exercise" edge to the WorkoutExercise entity by IDs.
func (wuo *WorkoutUpdateOne) AddWorkoutExerciseIDs(ids ...int) *WorkoutUpdateOne {
	wuo.mutation.AddWorkoutExerciseIDs(ids...)
	return wuo
}

// AddWorkoutExercise adds the "workout_exercise" edges to the WorkoutExercise entity.
func (wuo *WorkoutUpdateOne) AddWorkoutExercise(w ...*WorkoutExercise) *WorkoutUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.AddWorkoutExerciseIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (wuo *WorkoutUpdateOne) SetUser(u *User) *WorkoutUpdateOne {
	return wuo.SetUserID(u.ID)
}

// Mutation returns the WorkoutMutation object of the builder.
func (wuo *WorkoutUpdateOne) Mutation() *WorkoutMutation {
	return wuo.mutation
}

// ClearWorkoutExercise clears all "workout_exercise" edges to the WorkoutExercise entity.
func (wuo *WorkoutUpdateOne) ClearWorkoutExercise() *WorkoutUpdateOne {
	wuo.mutation.ClearWorkoutExercise()
	return wuo
}

// RemoveWorkoutExerciseIDs removes the "workout_exercise" edge to WorkoutExercise entities by IDs.
func (wuo *WorkoutUpdateOne) RemoveWorkoutExerciseIDs(ids ...int) *WorkoutUpdateOne {
	wuo.mutation.RemoveWorkoutExerciseIDs(ids...)
	return wuo
}

// RemoveWorkoutExercise removes "workout_exercise" edges to WorkoutExercise entities.
func (wuo *WorkoutUpdateOne) RemoveWorkoutExercise(w ...*WorkoutExercise) *WorkoutUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.RemoveWorkoutExerciseIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (wuo *WorkoutUpdateOne) ClearUser() *WorkoutUpdateOne {
	wuo.mutation.ClearUser()
	return wuo
}

// Where appends a list predicates to the WorkoutUpdate builder.
func (wuo *WorkoutUpdateOne) Where(ps ...predicate.Workout) *WorkoutUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkoutUpdateOne) Select(field string, fields ...string) *WorkoutUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workout entity.
func (wuo *WorkoutUpdateOne) Save(ctx context.Context) (*Workout, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkoutUpdateOne) SaveX(ctx context.Context) *Workout {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkoutUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkoutUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WorkoutUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdatedAt(); !ok {
		v := workout.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
}

func (wuo *WorkoutUpdateOne) sqlSave(ctx context.Context) (_node *Workout, err error) {
	_spec := sqlgraph.NewUpdateSpec(workout.Table, workout.Columns, sqlgraph.NewFieldSpec(workout.FieldID, field.TypeUUID))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workout.FieldID)
		for _, f := range fields {
			if !workout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workout.FieldName, field.TypeString, value)
	}
	if wuo.mutation.NameCleared() {
		_spec.ClearField(workout.FieldName, field.TypeString)
	}
	if value, ok := wuo.mutation.Active(); ok {
		_spec.SetField(workout.FieldActive, field.TypeBool, value)
	}
	if wuo.mutation.WorkoutExerciseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workout.WorkoutExerciseTable,
			Columns: []string{workout.WorkoutExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedWorkoutExerciseIDs(); len(nodes) > 0 && !wuo.mutation.WorkoutExerciseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workout.WorkoutExerciseTable,
			Columns: []string{workout.WorkoutExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.WorkoutExerciseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workout.WorkoutExerciseTable,
			Columns: []string{workout.WorkoutExerciseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workoutexercise.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UserTable,
			Columns: []string{workout.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workout.UserTable,
			Columns: []string{workout.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workout{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
