// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Exercise is the predicate function for exercise builders.
type Exercise func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workout is the predicate function for workout builders.
type Workout func(*sql.Selector)

// WorkoutExercise is the predicate function for workoutexercise builders.
type WorkoutExercise func(*sql.Selector)
